#pragma once

#include <memory>
#include <stdexcept>
#include <vector>

#include <BinaryCodeWord/BinaryCodeWord.hpp>

class BinaryCodeGenMat {
public:
    // Empty, uninitialized matrix
    BinaryCodeGenMat() = default;

    // Value semantics (deep copy of rows)
    BinaryCodeGenMat(const BinaryCodeGenMat& other);
    BinaryCodeGenMat& operator=(const BinaryCodeGenMat& other);
    BinaryCodeGenMat(BinaryCodeGenMat&& other) noexcept = default;
    BinaryCodeGenMat& operator=(BinaryCodeGenMat&& other) noexcept = default;
    virtual ~BinaryCodeGenMat() = default;

    // Supply rows (before initialize)
    void pushRow(const BinaryCodeWord& row);

    // Freeze staged rows into internal array (not vector)
    void initialize();

    bool initialized() const noexcept { return m_initialized; }

    int length() const;
    int numRows() const;
    BinaryCodeWord row(int i) const { return (*this)[i]; }

    // Access ORIGINAL supplied rows
    const BinaryCodeWord& operator[](int i) const;
    BinaryCodeWord& operator[](int i);

    // Codeword multiplied by Generator matrix
    friend BinaryCodeWord operator*(const BinaryCodeWord& u, const BinaryCodeGenMat& G);

    // Return NEW matrix in systematic form
    BinaryCodeGenMat getSystematic() const;

    // Compute the dimension of the code generated by this matrix (rank over GF(2)).
    // Uses row operations only and does not mutate the matrix.
    int getDim() const;

    // Return NEW matrix which is the transpose of this one.
    // If this is k x n (numRows x length), transpose is n x k.
    BinaryCodeGenMat transpose() const;

    // Matrix arithmetic over GF(2)
    BinaryCodeGenMat& operator+=(const BinaryCodeGenMat& rhs);
    BinaryCodeGenMat& operator*=(const BinaryCodeGenMat& rhs);

    friend BinaryCodeGenMat operator+(BinaryCodeGenMat lhs, const BinaryCodeGenMat& rhs) {
        lhs += rhs;
        return lhs;
    }
    friend BinaryCodeGenMat operator*(BinaryCodeGenMat lhs, const BinaryCodeGenMat& rhs) {
        lhs *= rhs;
        return lhs;
    }

    bool operator==(const BinaryCodeGenMat& rhs) const;
    bool operator!=(const BinaryCodeGenMat& rhs) const { return !(*this == rhs); }

    void swapColumns(int c1, int c2);

private:
    bool m_initialized{false};
    int m_length{0};
    int m_numRows{0};

    // staging area
    std::vector<BinaryCodeWord> m_staging;

    // stored original rows
    std::unique_ptr<BinaryCodeWord[]> m_rows;

private:
    void requireInitialized() const;
    void requireValidIndex(int i) const;

    static void swapColumns(std::vector<BinaryCodeWord>& rows, int c1, int c2);
};

// A square binary matrix is a generator matrix with length == numRows().
class BinarySquareMatrix : public BinaryCodeGenMat {
public:
    using BinaryCodeGenMat::BinaryCodeGenMat;

    // Computes (*this)^exp using successive squaring over GF(2).
    // exp must be >= 0.
    BinarySquareMatrix power(int exp) const;
};

// Identity matrix over GF(2)
class BinaryIdentityMatrix : public BinarySquareMatrix {
public:
    BinaryIdentityMatrix() = default;
    explicit BinaryIdentityMatrix(int size);

    void setSize(int size);
};

